### ISSUE TITLE
sddm theme errors

### ISSUE THREAD

**Issue by preceptsofzote** [heisenburgh/pixarch#3]
i am not sure if i am just missing something altogether, but the readme says pixarch will be using lightdm, and the only theme i can find for anything login related is an sddm theme in the boot folder.
i attempted to get that working, but it throws an error in the preview stating it has an Expected token 'numeric literal' in Main.qml.
i can half fix it by swapping the Main.qml with another themes Main.qml, but obviously that doesn't give the desired look.
any ideas?

**Comment by heisenburgh** [comment]
The readme is a bit outdated. We selected SDDM as a last minute choice rather than LightDM because the LightDM themeing was posing some issues.

Regarding the error, can you provide me with a screenshot or the complete error message?
Thanks

**Comment by preceptsofzote** [comment]
loading the sddm theme in sddm-config-editor shows the default sddm theme, and then a red note that says "The current Theme cannot be loaded due to the errors below, please select another theme.
file:///usr/share/sddm/themes/pixarch_sddm/Main.qml:297:1 Expected token `Numeric literal`"
if i try and install it manually it just doesn't run the theme at all.

**Comment by heisenburgh** [comment]
I have made some changes. 
Pull and check again, please

**Comment by preceptsofzote** [comment]
looks to have fixed it! thanks!
